import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, Section } from "@/components/LegalPage";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Nyrava" },
      { name: "description", content: "Terms governing use of the Nyrava platform." },
      { property: "og:title", content: "Terms of Service \u2014 Nyrava" },
      { property: "og:description", content: "Terms governing use of the Nyrava platform." },
      { property: "og:url", content: "https://nyrava.com/terms" },
      { name: "twitter:url", content: "https://nyrava.com/terms" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of Service"
      updated="2026-07-18"
      intro={
        <p>
          These terms describe the basis on which Nyrava is offered. This is a
          starting-point document intended to be reviewed and finalized by
          qualified counsel before being relied on as your final agreement.
        </p>
      }
    >
      <Section heading="Acceptable Use">
        <p>
          You agree to use Nyrava for lawful legal-analysis workflows. You will
          not upload content you do not have the right to process, and you will
          not attempt to disrupt or reverse-engineer the service.
        </p>
      </Section>

      <Section heading="Your Content">
        <p>
          You retain ownership of the case data, documents, and work product
          you create in Nyrava. We process that content only to operate the
          features you invoke.
        </p>
      </Section>

      <Section heading="No Legal Advice">
        <p>
          Nyrava provides software tools that assist qualified legal
          professionals. Outputs generated by the platform are analytical
          drafts, not legal advice, and must be reviewed by a qualified
          professional before being relied on.
        </p>
      </Section>

      <Section heading="AI-Assisted Output">
        <p>
          Analyses may contain errors or omissions. Users are responsible for
          verifying all AI-assisted output against source documents and
          applicable law. See <a href="/ai-transparency" className="text-primary hover:underline">AI Transparency</a>.
        </p>
      </Section>

      <Section heading="Disclaimers">
        <p>
          The service is provided "as is" without warranties of any kind,
          express or implied, to the maximum extent permitted by law. Nyrava
          does not warrant uninterrupted or error-free operation.
        </p>
      </Section>

      <Section heading="Termination">
        <p>
          Either party may terminate the relationship at any time. On
          termination, you may request export or deletion of your data through
          the <a href="/contact" className="text-primary hover:underline">Contact</a> page.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          We may update these terms from time to time. Material changes will be
          announced within the app.
        </p>
      </Section>
    </LegalPage>
  );
}
