// =============================================================================
// GENERATED POLICY DATA — Mexican materias (jurisdicción MX, sistema civil).
//
// Which engines may run, which finding modules may persist, which motion
// families may be drafted, which report sections render and which terms are
// forbidden in prose — all keyed by the canonical Mexican materia
// (MexicanCaseType). There is exactly one such table set in the codebase;
// src/lib/jurisdiction/mexico.ts is the only module that reads it.
// =============================================================================
import type { MexicanCaseType } from "./mexico-types";

export const MX_SECTIONS: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "civil": [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "mercantil": [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "familiar": [
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "laboral": [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "administrativo": [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "fiscal": [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "amparo": [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "constitucional": [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "electoral": [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "agrario": [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "ambiental": [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories"
  ],
  "inmobiliario": [
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "transaction_center"
  ]
};

export const MX_TABS: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "civil": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "mercantil": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "familiar": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories"
  ],
  "laboral": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "administrativo": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "fiscal": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "amparo": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "constitucional": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "electoral": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "agrario": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "ambiental": [
    "opportunities",
    "perspectives",
    "scorecard",
    "strategy",
    "theories",
    "trial"
  ],
  "inmobiliario": [
    "opportunities",
    "perspectives",
    "scorecard",
    "transaction_center"
  ]
};

export const MX_ENGINES: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep"
  ],
  "civil": [
    "cross_examination",
    "trial_prep"
  ],
  "mercantil": [
    "cross_examination",
    "trial_prep"
  ],
  "familiar": [],
  "laboral": [
    "trial_prep"
  ],
  "administrativo": [
    "cross_examination",
    "trial_prep"
  ],
  "fiscal": [
    "cross_examination",
    "trial_prep"
  ],
  "amparo": [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep"
  ],
  "constitucional": [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep"
  ],
  "electoral": [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep"
  ],
  "agrario": [
    "cross_examination",
    "trial_prep"
  ],
  "ambiental": [
    "constitutional_compliance",
    "cross_examination",
    "trial_prep"
  ],
  "inmobiliario": [
    "property_verification",
    "closing_readiness_scoring"
  ]
};

export const MX_FINDING_MODULES: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "cadena_de_custodia",
    "carpeta_de_investigacion",
    "datos_de_prueba",
    "debido_proceso",
    "defensa_adecuada",
    "defraudacion_fiscal",
    "false_return",
    "individualizacion_sancion",
    "medidas_cautelares",
    "presuncion_de_inocencia",
    "prision_preventiva_oficiosa",
    "procedural",
    "salidas_alternas",
    "tax_evasion",
    "trial_strategy",
    "vinculacion_a_proceso",
    "willfulness"
  ],
  "civil": [
    "adverse_possession",
    "boundary_dispute",
    "cam_charges",
    "causation",
    "cc_and_r",
    "ceqa",
    "chain_of_title",
    "civil_procedure_mx",
    "closing",
    "closing_disclosure",
    "commercial_lease",
    "comparative_fault",
    "condemnation",
    "conditional_use",
    "constructive_eviction",
    "contrato",
    "covenants",
    "cumplimiento_forzoso",
    "damages",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "deed",
    "deed_of_trust",
    "deficiency_judgment",
    "disclosure_violation",
    "easement",
    "eminent_domain",
    "encumbrance",
    "enriquecimiento_ilegitimo",
    "escrow",
    "eviction",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "expert_testimony",
    "foreclosure",
    "future_damages",
    "gestion_de_negocios",
    "grant_deed",
    "habitability",
    "hecho_ilicito",
    "hoa",
    "incumplimiento_contractual",
    "informed_consent",
    "inverse_condemnation",
    "judicial_foreclosure",
    "land_use",
    "landlord_tenant",
    "lease",
    "liability",
    "lien",
    "lost_wages",
    "marketable_title",
    "mechanics_lien",
    "medical_records",
    "medical_timeline",
    "medical_treatment",
    "mora",
    "mortgage",
    "negligence",
    "nepa",
    "non_judicial_foreclosure",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "premises",
    "prescripcion_negativa",
    "prescriptive_easement",
    "purchase_agreement",
    "quiet_enjoyment",
    "quiet_title",
    "quitclaim",
    "real_estate_discovery",
    "real_estate_motion",
    "recording",
    "redemption",
    "regulatory_taking",
    "reinstatement",
    "rescision_contractual",
    "respa",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "restrictive_covenants",
    "sale_agreement",
    "security_deposit",
    "standard_of_care",
    "subdivision",
    "tila",
    "title",
    "title_defect",
    "title_insurance",
    "unlawful_detainer",
    "variance",
    "vicios_del_consentimiento",
    "warranty_deed",
    "zoning"
  ],
  "mercantil": [
    "10b_5",
    "13d",
    "13g",
    "acceleration",
    "accredited_investor",
    "ach",
    "acquisition",
    "adequate_protection",
    "administrative_proceeding",
    "advisers_act",
    "aml",
    "aml_travel_rule",
    "anticipation",
    "anticipatory_repudiation",
    "arbitration_clause",
    "articles_of_incorporation",
    "asset_purchase",
    "assignment",
    "assignment_of_loan",
    "attachment",
    "authorship",
    "automatic_stay",
    "baas",
    "bank_partnership",
    "bank_secrecy_act",
    "banking_as_a_service",
    "banking_discovery",
    "banking_motion",
    "bankruptcy_stay",
    "basic_v_levinson",
    "beneficial_ownership",
    "bnpl",
    "board_minutes",
    "board_resolution",
    "books_and_records",
    "breach",
    "breach_of_contract",
    "bsa",
    "business_judgment",
    "buy_now_pay_later",
    "bylaws",
    "card_network",
    "caremark",
    "cash_collateral",
    "ccpa",
    "cease_and_desist",
    "cfpb",
    "chain_of_title",
    "choice_of_law",
    "cip",
    "civil_penalty",
    "claim_construction",
    "classical_theory",
    "clawback",
    "cold_storage",
    "collateral",
    "commercial_discovery",
    "commercial_impracticability",
    "commercial_motion",
    "commercially_reasonable",
    "commitment_letter",
    "conditions_precedent",
    "conflict_of_interest",
    "conforming_goods",
    "consequential_damages",
    "consumer_finance",
    "contract",
    "contract_formation",
    "contract_interpretation",
    "copyright",
    "copyright_infringement",
    "corporate_compliance",
    "corporate_disclosure",
    "corporate_dissolution",
    "corporate_governance",
    "corporate_governance_gap",
    "corporate_minutes",
    "cover",
    "cpra",
    "cra",
    "credit_agreement",
    "cross_collateralization",
    "cross_default",
    "cryptocurrency",
    "ctr",
    "cure",
    "custody_of_digital_assets",
    "cybersecurity",
    "damages",
    "data_privacy",
    "default",
    "defend_trade_secrets_act",
    "defi",
    "deficiency",
    "delegation",
    "derivative_action",
    "derivative_work",
    "descriptive_fair_use",
    "dex",
    "digital_asset",
    "dilution",
    "dip_financing",
    "director_liability",
    "disclaimer",
    "disgorgement",
    "dmca",
    "doctrine_of_equivalents",
    "dodd_frank",
    "dtsa",
    "due_diligence",
    "durbin_amendment",
    "duty_of_care",
    "duty_of_good_faith",
    "duty_of_loyalty",
    "e_sign",
    "earned_wage_access",
    "ecoa",
    "electronic_signature",
    "entity_structure",
    "escrow",
    "event_of_default",
    "ewa",
    "express_warranty",
    "fair_lending",
    "fair_use",
    "fiduciary_duty",
    "finCEN",
    "financing_statement",
    "fintech_discovery",
    "fintech_motion",
    "fitness_particular_purpose",
    "flood_disaster_protection_act",
    "forbearance",
    "force_majeure",
    "foreclosure",
    "form_10_k",
    "form_10_q",
    "form_8_k",
    "forum_selection",
    "fraud_in_inducement",
    "fraud_on_the_market",
    "fraudulent_transfer",
    "gdpr",
    "genericness",
    "gift_card",
    "glba",
    "goods",
    "guaranty",
    "hmda",
    "howey_test",
    "ica",
    "icfr",
    "implied_warranty",
    "improper_means",
    "indemnity_clause",
    "inequitable_conduct",
    "injunction",
    "insider_trading",
    "installment_loan",
    "interchange",
    "intercreditor",
    "interference_with_contract",
    "interference_with_prospective_advantage",
    "internal_controls",
    "inventorship",
    "investment_adviser",
    "investment_company_act",
    "ip_discovery",
    "ip_motion",
    "ip_ownership",
    "item_303",
    "kyc",
    "lanham_act",
    "lead_plaintiff",
    "letter_of_credit",
    "license_scope",
    "licensing",
    "likelihood_of_confusion",
    "limitation_of_liability",
    "liquidated_damages",
    "loan_agreement",
    "loan_participation",
    "loss_causation",
    "markman",
    "material_breach",
    "material_misstatement",
    "material_omission",
    "mdna",
    "merchantability",
    "merger",
    "misappropriation",
    "misappropriation_theory",
    "misrepresentation",
    "mitigation",
    "modification",
    "money_transmission",
    "money_transmitter_license",
    "msb",
    "mtl",
    "nacha",
    "negligent_misrepresentation",
    "nominative_fair_use",
    "novation",
    "nydfs_500",
    "obviousness",
    "ofac",
    "officer_liability",
    "operating_agreement",
    "part_500",
    "particularity",
    "patent",
    "patent_eligibility",
    "patent_infringement",
    "payment_processor",
    "payments",
    "perfect_tender",
    "perfection",
    "pmsi",
    "preference",
    "prepaid_card",
    "prior_art",
    "priority",
    "promissory_estoppel",
    "promissory_note",
    "prosecution_history_estoppel",
    "prospectus",
    "pslra",
    "psp",
    "purchase_money_security_interest",
    "qualified_custodian",
    "quantum_meruit",
    "reasonable_secrecy_measures",
    "reformation",
    "registration",
    "registration_statement",
    "regulation_a",
    "regulation_b",
    "regulation_d",
    "regulation_e",
    "regulation_e_error_resolution",
    "regulation_fd",
    "regulation_o",
    "regulation_s",
    "regulation_w",
    "regulation_z",
    "reliance",
    "relief_from_stay",
    "repossession",
    "rescission",
    "respa",
    "reves_test",
    "revlon",
    "revocation_of_acceptance",
    "revolver",
    "revolving_credit",
    "risk_factor",
    "royalty",
    "rule_10b_5",
    "rule_506",
    "s_1",
    "s_3",
    "s_4",
    "safe_harbor",
    "safe_harbor_forward_looking",
    "sale_of_goods",
    "same_day_ach",
    "sanctions",
    "sar",
    "sarbanes_oxley",
    "scienter",
    "screening",
    "sec_enforcement",
    "secondary_meaning",
    "section_101",
    "section_102",
    "section_103",
    "section_11",
    "section_112",
    "section_12",
    "section_15",
    "section_16",
    "section_220",
    "section_302",
    "section_404",
    "section_906",
    "securities_class_action",
    "securities_discovery",
    "securities_motion",
    "security_agreement",
    "security_token",
    "self_dealing",
    "self_help",
    "servicing",
    "shareholder_agreement",
    "short_swing",
    "smart_contract",
    "sox",
    "specific_performance",
    "sponsor_bank",
    "stablecoin",
    "state_licensing",
    "stock_purchase",
    "strict_foreclosure",
    "subordination",
    "substantial_similarity",
    "surety",
    "surplus",
    "syndicated_loan",
    "term_loan",
    "term_sheet",
    "third_party_beneficiary",
    "tila",
    "tipping",
    "token",
    "tortious_interference",
    "trade_dress",
    "trade_secret",
    "trademark",
    "trademark_infringement",
    "transaction_causation",
    "true_lender",
    "truth_in_lending",
    "ucc_1",
    "ucc_article_2",
    "ucc_article_9",
    "udaap",
    "ueta",
    "unfair_competition",
    "unjust_enrichment",
    "unocal",
    "usury",
    "utility_token",
    "utsa",
    "vasp",
    "waiver_and_amendment",
    "waiver_estoppel",
    "warranty",
    "wells_notice",
    "wells_submission",
    "whistleblower",
    "willful_infringement",
    "wire",
    "work_for_hire",
    "workout"
  ],
  "familiar": [
    "advance_directive",
    "attestation",
    "beneficiary_designation",
    "best_interests",
    "capacity",
    "charitable_deduction",
    "child_support",
    "codicil",
    "community_property",
    "conservatorship",
    "custody",
    "duress",
    "duty_of_impartiality",
    "duty_of_loyalty",
    "duty_to_account",
    "elective_share",
    "estate_discovery",
    "estate_motion",
    "estate_tax",
    "fiduciary_duty",
    "fraud_in_execution",
    "gift_tax",
    "gst",
    "guardianship",
    "holographic_will",
    "in_terrorem",
    "intestate",
    "intestate_succession",
    "irrevocable_trust",
    "joint_tenancy",
    "letters_of_administration",
    "letters_testamentary",
    "marital_deduction",
    "no_contest_clause",
    "omitted_child",
    "omitted_spouse",
    "parenting",
    "petition_for_instructions",
    "petition_for_probate",
    "pod",
    "portability",
    "pour_over",
    "power_of_attorney",
    "pretermitted_heir",
    "probate",
    "property_division",
    "prudent_investor",
    "revocable_trust",
    "revocation",
    "self_dealing",
    "self_proving_affidavit",
    "spendthrift",
    "spousal_support",
    "testamentary_capacity",
    "tod",
    "trust",
    "trust_amendment",
    "trust_contest",
    "trust_restatement",
    "trustee_duty",
    "undue_influence",
    "visitation",
    "will",
    "will_contest",
    "witness_requirement"
  ],
  "laboral": [
    "ada",
    "discrimination",
    "eeoc",
    "fmla",
    "harassment",
    "hostile_work",
    "hr_records",
    "payroll",
    "retaliation",
    "wage_hour",
    "wrongful_termination"
  ],
  "administrativo": [
    "audit_reconsideration",
    "burden_of_proof",
    "civil_procedure_mx",
    "collection_due_process",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "gestion_de_negocios",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "innocent_spouse",
    "mora",
    "notice_of_deficiency",
    "nulidad_absoluta",
    "nulidad_relativa",
    "offer_in_compromise",
    "ofrecimiento_de_pruebas",
    "penalty_abatement",
    "prescripcion_negativa",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "tax_court",
    "tax_deficiency",
    "tax_levy",
    "tax_liability",
    "tax_lien",
    "vicios_del_consentimiento"
  ],
  "fiscal": [
    "audit_reconsideration",
    "burden_of_proof",
    "collection_due_process",
    "innocent_spouse",
    "notice_of_deficiency",
    "offer_in_compromise",
    "penalty_abatement",
    "tax_court",
    "tax_deficiency",
    "tax_levy",
    "tax_liability",
    "tax_lien"
  ],
  "amparo": [
    "acto_reclamado",
    "autoridad_responsable",
    "brady",
    "conceptos_de_violacion",
    "constitutional",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "giglio",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "monell",
    "procedencia",
    "procedural",
    "qualified_immunity",
    "section_1983",
    "suplencia_de_la_queja",
    "suspension",
    "violacion_derechos_humanos"
  ],
  "constitucional": [
    "acto_reclamado",
    "autoridad_responsable",
    "brady",
    "conceptos_de_violacion",
    "constitutional",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "giglio",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "monell",
    "procedencia",
    "procedural",
    "qualified_immunity",
    "section_1983",
    "suplencia_de_la_queja",
    "suspension",
    "violacion_derechos_humanos"
  ],
  "electoral": [
    "brady",
    "civil_procedure_mx",
    "constitutional",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "gestion_de_negocios",
    "giglio",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "monell",
    "mora",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "prescripcion_negativa",
    "procedural",
    "qualified_immunity",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "section_1983",
    "vicios_del_consentimiento"
  ],
  "agrario": [
    "civil_procedure_mx",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "gestion_de_negocios",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "mora",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "prescripcion_negativa",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "vicios_del_consentimiento"
  ],
  "ambiental": [
    "autorizacion_cambio_uso_suelo",
    "clausura_profepa",
    "concesion_agua_conagua",
    "dano_ambiental",
    "denuncia_popular_ambiental",
    "descarga_aguas_residuales",
    "emisiones_contaminantes",
    "estudio_riesgo_ambiental",
    "gases_efecto_invernadero",
    "licencia_ambiental_unica",
    "manifestacion_impacto_ambiental",
    "medidas_de_seguridad_profepa",
    "nom_ambiental_incumplimiento",
    "permiso_forestal_conafor",
    "procedimiento_administrativo_profepa",
    "proteccion_areas_naturales_conanp",
    "recurso_de_revision_ambiental",
    "regulacion_industria_hidrocarburos_asea",
    "remediacion_ambiental",
    "residuos_peligrosos",
    "responsabilidad_ambiental_objetiva"
  ],
  "inmobiliario": [
    "adeudo_agua",
    "adeudo_cfe",
    "adeudo_hoa",
    "adeudo_predial",
    "cancelacion_hipoteca",
    "catastro",
    "cuenta_predial",
    "discrepancia_medidas",
    "discrepancia_propietario",
    "documento_faltante",
    "documento_vencido",
    "escritura_publica",
    "fideicomiso_zona_restringida",
    "firma_faltante",
    "folio_real",
    "gravamen",
    "hipoteca_vigente",
    "levantamiento_topografico",
    "libertad_de_gravamen",
    "permiso_construccion",
    "poder_notarial",
    "uso_de_suelo"
  ]
};

export const MX_MOTION_TYPES: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "acuerdo_reparatorio",
    "amparo_indirecto_penal",
    "impugnacion_medidas_cautelares",
    "procedimiento_abreviado",
    "recurso_de_apelacion",
    "solicitud_de_no_vinculacion",
    "suspension_condicional"
  ],
  "civil": [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "compel",
    "contestacion_demanda",
    "daubert",
    "demanda_civil",
    "discovery",
    "dismiss",
    "expert",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "interplead_escrow",
    "lis_pendens",
    "ofrecimiento_pruebas",
    "preliminary_injunction",
    "protective_order",
    "providencias_precautorias",
    "quiet_title",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "specific_performance",
    "summary_judgment",
    "unlawful_detainer"
  ],
  "mercantil": [
    "amend",
    "appointment_of_receiver",
    "asset_purchase_agreement",
    "attachment",
    "board_resolution",
    "books_and_records",
    "breach_of_contract",
    "claim_construction_brief",
    "class_certification",
    "compel",
    "compel_arbitration",
    "confess_judgment",
    "confirm_arbitration",
    "corporate_minutes",
    "daubert",
    "declaratory_judgment",
    "derivative",
    "derivative_action",
    "disclosure_schedule",
    "discovery",
    "dismiss",
    "due_diligence_request",
    "expedited_proceedings",
    "expert",
    "judgment_on_pleadings",
    "lead_plaintiff_motion",
    "markman_hearing",
    "merger_approval",
    "motion_to_dismiss_pslra",
    "partial_summary_judgment",
    "permanent_injunction",
    "preliminary_injunction",
    "protective_order",
    "relief_from_stay",
    "remand",
    "replevin",
    "sanctions",
    "section_220",
    "seizure_order",
    "sequestration",
    "shareholder_consent",
    "specific_performance",
    "stay_pending_arbitration",
    "stock_purchase_agreement",
    "summary_judgment",
    "temporary_restraining_order",
    "tro",
    "vacate_arbitration"
  ],
  "familiar": [
    "compel",
    "contempt",
    "custody_modification",
    "discovery",
    "dismiss",
    "petition_for_instructions",
    "petition_for_probate",
    "petition_to_compel_accounting",
    "petition_to_remove_fiduciary",
    "protective_order",
    "summary_judgment",
    "support_modification",
    "temporary_orders",
    "trust_contest",
    "visitation",
    "will_contest"
  ],
  "laboral": [
    "class_certification",
    "compel",
    "discovery",
    "protective_order",
    "summary_judgment"
  ],
  "administrativo": [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "collection_due_process",
    "compel",
    "contestacion_demanda",
    "deficiency",
    "demanda_civil",
    "discovery",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "innocent_spouse",
    "offer_in_compromise",
    "ofrecimiento_pruebas",
    "providencias_precautorias",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "refund_suit",
    "summary_judgment",
    "tax_court_petition"
  ],
  "fiscal": [
    "collection_due_process",
    "compel",
    "deficiency",
    "discovery",
    "innocent_spouse",
    "offer_in_compromise",
    "refund_suit",
    "summary_judgment",
    "tax_court_petition"
  ],
  "amparo": [
    "demanda_de_amparo",
    "discovery",
    "incidente_de_suspension",
    "preliminary_injunction",
    "qualified_immunity",
    "recurso_de_queja",
    "recurso_de_revision",
    "section_1983",
    "summary_judgment"
  ],
  "constitucional": [
    "demanda_de_amparo",
    "discovery",
    "incidente_de_suspension",
    "preliminary_injunction",
    "qualified_immunity",
    "recurso_de_queja",
    "recurso_de_revision",
    "section_1983",
    "summary_judgment"
  ],
  "electoral": [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "contestacion_demanda",
    "demanda_civil",
    "discovery",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_pruebas",
    "preliminary_injunction",
    "providencias_precautorias",
    "qualified_immunity",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "section_1983",
    "summary_judgment"
  ],
  "agrario": [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "contestacion_demanda",
    "demanda_civil",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_pruebas",
    "providencias_precautorias",
    "reconvencion",
    "recurso_de_apelacion_civil"
  ],
  "ambiental": [
    "amparo_indirecto_ambiental",
    "denuncia_popular",
    "impugnacion_negativa_concesion_conagua",
    "impugnacion_permiso_forestal_conafor",
    "incidente_suspension_profepa",
    "juicio_de_nulidad_ambiental",
    "medidas_cautelares_ambientales",
    "ofrecimiento_pruebas",
    "recurso_de_revision"
  ],
  // Deliberately empty: a closing has no motions. If a real estate matter
  // ever needs one, it has become a dispute — i.e. civil, not inmobiliario.
  "inmobiliario": []
};

export const MX_BLOCKED_TERMS: Record<MexicanCaseType, readonly string[]> = {
  "penal": [
    "child custody",
    "custody dispute",
    "discrimination claim",
    "district attorney",
    "felony",
    "grand jury",
    "miranda",
    "misdemeanor",
    "payroll records",
    "plea bargain",
    "spousal support",
    "title vii",
    "wrongful termination"
  ],
  "civil": [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "medical malpractice",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "standard of care",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination"
  ],
  "mercantil": [
    "brady violation",
    "child custody",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "standard of care",
    "title vii",
    "wrongful termination"
  ],
  "familiar": [
    "brady violation",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "standard of care",
    "title vii",
    "wrongful termination"
  ],
  "laboral": [
    "brady violation",
    "child custody",
    "criminal procedure",
    "indictment",
    "miranda",
    "spousal support"
  ],
  "administrativo": [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination"
  ],
  "fiscal": [
    "child custody",
    "criminal procedure",
    "grand jury",
    "indictment",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "title vii",
    "wrongful termination"
  ],
  "amparo": [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support"
  ],
  "constitucional": [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support"
  ],
  "electoral": [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "divorce",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "payroll records",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination"
  ],
  "agrario": [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination"
  ],
  "ambiental": [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination"
  ],
  "inmobiliario": [
    "cross examination",
    "custody dispute",
    "grand jury",
    "hearsay",
    "indictment",
    "jury trial",
    "miranda",
    "motion to dismiss",
    "plea bargain",
    "punitive damages",
    "sentencing",
    "spousal support",
    "subpoena",
    "trial strategy",
    "wrongful termination"
  ]
};

export const MX_FORBIDDEN_REPORT_FIELDS: Record<MexicanCaseType, readonly string[]> = {
  "penal": [],
  "civil": [
    "constitutional_issues",
    "constitutional_issues_struct"
  ],
  "mercantil": [
    "constitutional_issues",
    "constitutional_issues_struct"
  ],
  "familiar": [
    "constitutional_issues",
    "constitutional_issues_struct",
    "cross_examination"
  ],
  "laboral": [
    "constitutional_issues",
    "constitutional_issues_struct",
    "cross_examination"
  ],
  "administrativo": [
    "constitutional_issues",
    "constitutional_issues_struct"
  ],
  "fiscal": [
    "constitutional_issues",
    "constitutional_issues_struct"
  ],
  "amparo": [],
  "constitucional": [],
  "electoral": [],
  "agrario": [
    "constitutional_issues",
    "constitutional_issues_struct"
  ],
  "ambiental": [],
  "inmobiliario": [
    "constitutional_issues",
    "constitutional_issues_struct",
    "cross_examination"
  ]
};

