// =============================================================================
// GENERATED POLICY DATA — Mexican materias (jurisdicción MX, sistema civil).
//
// Which engines may run, which finding modules may persist, which motion
// families may be drafted, which report sections render and which terms are
// forbidden in prose — all keyed by the canonical Mexican materia
// (MexicanCaseType). There is exactly one such table set in the codebase;
// src/lib/jurisdiction/mexico.ts is the only module that reads it.
// =============================================================================
import type { MexicanCaseType } from "./mexico-types";

export const MX_SECTIONS: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  civil: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  mercantil: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  familiar: ["opportunities", "perspectives", "recommendations", "risk", "scorecard", "strategy_synthesis", "theories"],
  laboral: [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  administrativo: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  fiscal: [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  amparo: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  constitucional: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  electoral: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  agrario: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  ambiental: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  inmobiliario: ["opportunities", "perspectives", "recommendations", "risk", "scorecard", "transaction_center"],
};

export const MX_TABS: Record<MexicanCaseType, readonly string[]> = {
  penal: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  civil: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  mercantil: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  familiar: ["opportunities", "perspectives", "scorecard", "strategy", "theories"],
  laboral: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  administrativo: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  fiscal: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  amparo: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  constitucional: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  electoral: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  agrario: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  ambiental: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial"],
  inmobiliario: ["opportunities", "perspectives", "scorecard", "transaction_center"],
};

export const MX_ENGINES: Record<MexicanCaseType, readonly string[]> = {
  penal: ["chain_of_custody", "constitutional_compliance", "cross_examination", "procedural_violations", "trial_prep"],
  civil: ["cross_examination", "trial_prep"],
  mercantil: ["cross_examination", "trial_prep"],
  familiar: [],
  laboral: ["trial_prep"],
  administrativo: ["cross_examination", "trial_prep"],
  fiscal: ["cross_examination", "trial_prep"],
  amparo: ["chain_of_custody", "constitutional_compliance", "cross_examination", "procedural_violations", "trial_prep"],
  constitucional: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep",
  ],
  electoral: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "trial_prep",
  ],
  agrario: ["cross_examination", "trial_prep"],
  ambiental: ["constitutional_compliance", "cross_examination", "trial_prep"],
  inmobiliario: ["property_verification", "closing_readiness_scoring"],
};

export const MX_FINDING_MODULES: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "cadena_de_custodia",
    "carpeta_de_investigacion",
    "datos_de_prueba",
    "debido_proceso",
    "defensa_adecuada",
    "defraudacion_fiscal",
    "false_return",
    "individualizacion_sancion",
    "medidas_cautelares",
    "presuncion_de_inocencia",
    "prision_preventiva_oficiosa",
    "procedural",
    "salidas_alternas",
    "tax_evasion",
    "trial_strategy",
    "vinculacion_a_proceso",
    "willfulness",
  ],
  civil: [
    "adverse_possession",
    "boundary_dispute",
    "cam_charges",
    "causation",
    "cc_and_r",
    "ceqa",
    "chain_of_title",
    "civil_procedure_mx",
    "closing",
    "closing_disclosure",
    "commercial_lease",
    "comparative_fault",
    "condemnation",
    "conditional_use",
    "constructive_eviction",
    "contrato",
    "covenants",
    "cumplimiento_forzoso",
    "damages",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "deed",
    "deed_of_trust",
    "deficiency_judgment",
    "disclosure_violation",
    "easement",
    "eminent_domain",
    "encumbrance",
    "enriquecimiento_ilegitimo",
    "escrow",
    "eviction",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "expert_testimony",
    "foreclosure",
    "future_damages",
    "gestion_de_negocios",
    "grant_deed",
    "habitability",
    "hecho_ilicito",
    "hoa",
    "incumplimiento_contractual",
    "informed_consent",
    "inverse_condemnation",
    "judicial_foreclosure",
    "land_use",
    "landlord_tenant",
    "lease",
    "liability",
    "lien",
    "lost_wages",
    "marketable_title",
    "mechanics_lien",
    "medical_records",
    "medical_timeline",
    "medical_treatment",
    "mora",
    "mortgage",
    "negligence",
    "nepa",
    "non_judicial_foreclosure",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "premises",
    "prescripcion_negativa",
    "prescriptive_easement",
    "purchase_agreement",
    "quiet_enjoyment",
    "quiet_title",
    "quitclaim",
    "real_estate_discovery",
    "real_estate_motion",
    "recording",
    "redemption",
    "regulatory_taking",
    "reinstatement",
    "rescision_contractual",
    "respa",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "restrictive_covenants",
    "sale_agreement",
    "security_deposit",
    "standard_of_care",
    "subdivision",
    "tila",
    "title",
    "title_defect",
    "title_insurance",
    "unlawful_detainer",
    "variance",
    "vicios_del_consentimiento",
    "warranty_deed",
    "zoning",
  ],
  // REBUILT 2026-07-29: this list previously contained ~345 entries of
  // U.S. federal securities, banking, and IP doctrine (10b_5, dodd_frank,
  // sarbanes_oxley, hmda, tila, respa, glba, pslra, cfpb, ecoa, lanham_act,
  // dmca, markman, howey_test, wells_notice, etc.) — none of which are
  // Mexican commercial law. Rebuilt from the actual governing framework:
  // Código de Comercio (juicio ejecutivo/oral mercantil), Ley General de
  // Títulos y Operaciones de Crédito (pagaré, letra de cambio, aval),
  // Ley General de Sociedades Mercantiles (asamblea, consejo de
  // administración, fusión/escisión), Ley de Concursos Mercantiles,
  // Ley del Mercado de Valores, Ley de Instituciones de Crédito, Ley para
  // Regular las Instituciones de Tecnología Financiera (Ley Fintech),
  // Ley Federal de Competencia Económica, Ley Federal de Protección a la
  // Propiedad Industrial, Ley Federal de Protección al Consumidor, and the
  // Ley Federal para la Prevención e Identificación de Operaciones con
  // Recursos de Procedencia Ilícita. This is a representative core
  // taxonomy, not a claim of exhaustive coverage — extend it as real case
  // material surfaces gaps, the same way the original (mis-scoped) list
  // grew over time.
  mercantil: [
    "pagare",
    "letra_de_cambio",
    "cheque",
    "aval",
    "endoso",
    "protesto",
    "accion_cambiaria",
    "caducidad_cambiaria",
    "prescripcion_cambiaria",
    "obligacion_cambiaria",
    "certificado_de_deposito",
    "bono_de_prenda",
    "obligacion_subordinada",
    "contrato_mercantil",
    "compraventa_mercantil",
    "contrato_de_suministro",
    "contrato_de_comision_mercantil",
    "contrato_de_deposito_mercantil",
    "contrato_de_transporte",
    "contrato_de_seguro",
    "contrato_de_fianza",
    "factoraje_financiero",
    "arrendamiento_financiero",
    "fideicomiso",
    "fideicomiso_de_garantia",
    "contrato_de_apertura_de_credito",
    "contrato_de_credito_simple",
    "contrato_de_credito_en_cuenta_corriente",
    "sociedad_anonima",
    "sociedad_de_responsabilidad_limitada",
    "sociedad_por_acciones_simplificada",
    "asamblea_de_accionistas",
    "asamblea_general_ordinaria",
    "asamblea_general_extraordinaria",
    "consejo_de_administracion",
    "administrador_unico",
    "capital_social",
    "partes_sociales",
    "comisario",
    "fusion",
    "escision",
    "liquidacion_societaria",
    "disolucion_societaria",
    "responsabilidad_de_administradores",
    "accion_de_responsabilidad",
    "estatutos_sociales",
    "acta_de_asamblea",
    "juicio_ejecutivo_mercantil",
    "juicio_oral_mercantil",
    "via_ejecutiva",
    "via_ordinaria_mercantil",
    "titulo_ejecutivo",
    "embargo_mercantil",
    "excepciones_procesales_mercantiles",
    "recurso_de_apelacion_mercantil",
    "prueba_pericial_mercantil",
    "auto_de_exequendo",
    "requerimiento_de_pago",
    "diligencia_de_embargo",
    "tercero_excluyente",
    "concurso_mercantil",
    "conciliacion_concursal",
    "quiebra",
    "sindico",
    "visitador",
    "conciliador",
    "masa_concursal",
    "reconocimiento_de_creditos",
    "declaracion_de_concurso_mercantil",
    "garantia_mobiliaria",
    "prenda_mercantil",
    "hipoteca_mercantil",
    "credito_mercantil",
    "interes_moratorio",
    "interes_ordinario",
    "usura",
    "tasa_de_interes_usuraria",
    "oferta_publica_de_valores",
    "emisora",
    "bolsa_mexicana_de_valores",
    "comision_nacional_bancaria_y_de_valores",
    "condusef",
    "banxico",
    "institucion_de_credito",
    "institucion_de_banca_multiple",
    "sofom",
    "sofipo",
    "ley_fintech",
    "institucion_de_tecnologia_financiera",
    "activo_virtual",
    "cuenta_de_fondos_de_pago_electronico",
    "competencia_economica",
    "cofece",
    "practica_monopolica",
    "concentracion_prohibida",
    "poder_sustancial_de_mercado",
    "propiedad_industrial",
    "marca",
    "patente",
    "nombre_comercial",
    "infraccion_administrativa",
    "impi",
    "aviso_comercial",
    "arbitraje_comercial",
    "clausula_compromisoria",
    "laudo_arbitral",
    "camara_de_comercio",
    "reconocimiento_y_ejecucion_de_laudo",
    "proteccion_al_consumidor",
    "profeco",
    "publicidad_enganosa",
    "clausula_abusiva",
    "operaciones_con_recursos_de_procedencia_ilicita",
    "unidad_de_inteligencia_financiera",
    "uif",
    "aviso_ante_la_uif",
  ],
  familiar: [
    "advance_directive",
    "attestation",
    "beneficiary_designation",
    "best_interests",
    "capacity",
    "charitable_deduction",
    "child_support",
    "codicil",
    "community_property",
    "conservatorship",
    "custody",
    "duress",
    "duty_of_impartiality",
    "duty_of_loyalty",
    "duty_to_account",
    "elective_share",
    "estate_discovery",
    "estate_motion",
    "estate_tax",
    "fiduciary_duty",
    "fraud_in_execution",
    "gift_tax",
    "gst",
    "guardianship",
    "holographic_will",
    "in_terrorem",
    "intestate",
    "intestate_succession",
    "irrevocable_trust",
    "joint_tenancy",
    "letters_of_administration",
    "letters_testamentary",
    "marital_deduction",
    "no_contest_clause",
    "omitted_child",
    "omitted_spouse",
    "parenting",
    "petition_for_instructions",
    "petition_for_probate",
    "pod",
    "portability",
    "pour_over",
    "power_of_attorney",
    "pretermitted_heir",
    "probate",
    "property_division",
    "prudent_investor",
    "revocable_trust",
    "revocation",
    "self_dealing",
    "self_proving_affidavit",
    "spendthrift",
    "spousal_support",
    "testamentary_capacity",
    "tod",
    "trust",
    "trust_amendment",
    "trust_contest",
    "trust_restatement",
    "trustee_duty",
    "undue_influence",
    "visitation",
    "will",
    "will_contest",
    "witness_requirement",
  ],
  laboral: [
    "ada",
    "discrimination",
    "eeoc",
    "fmla",
    "harassment",
    "hostile_work",
    "hr_records",
    "payroll",
    "retaliation",
    "wage_hour",
    "wrongful_termination",
  ],
  administrativo: [
    "audit_reconsideration",
    "burden_of_proof",
    "civil_procedure_mx",
    "collection_due_process",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "gestion_de_negocios",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "innocent_spouse",
    "mora",
    "notice_of_deficiency",
    "nulidad_absoluta",
    "nulidad_relativa",
    "offer_in_compromise",
    "ofrecimiento_de_pruebas",
    "penalty_abatement",
    "prescripcion_negativa",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "tax_court",
    "tax_deficiency",
    "tax_levy",
    "tax_liability",
    "tax_lien",
    "vicios_del_consentimiento",
  ],
  fiscal: [
    "audit_reconsideration",
    "burden_of_proof",
    "collection_due_process",
    "innocent_spouse",
    "notice_of_deficiency",
    "offer_in_compromise",
    "penalty_abatement",
    "tax_court",
    "tax_deficiency",
    "tax_levy",
    "tax_liability",
    "tax_lien",
  ],
  amparo: [
    "acto_reclamado",
    "autoridad_responsable",
    "brady",
    "conceptos_de_violacion",
    "constitutional",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "giglio",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "monell",
    "procedencia",
    "procedural",
    "qualified_immunity",
    "section_1983",
    "suplencia_de_la_queja",
    "suspension",
    "violacion_derechos_humanos",
  ],
  constitucional: [
    "acto_reclamado",
    "autoridad_responsable",
    "brady",
    "conceptos_de_violacion",
    "constitutional",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "giglio",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "monell",
    "procedencia",
    "procedural",
    "qualified_immunity",
    "section_1983",
    "suplencia_de_la_queja",
    "suspension",
    "violacion_derechos_humanos",
  ],
  electoral: [
    "brady",
    "civil_procedure_mx",
    "constitutional",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "excessive_force",
    "first_amendment",
    "fourth_amendment",
    "gestion_de_negocios",
    "giglio",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "monell",
    "mora",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "prescripcion_negativa",
    "procedural",
    "qualified_immunity",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "section_1983",
    "vicios_del_consentimiento",
  ],
  agrario: [
    "civil_procedure_mx",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "enriquecimiento_ilegitimo",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "gestion_de_negocios",
    "hecho_ilicito",
    "incumplimiento_contractual",
    "mora",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "prescripcion_negativa",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "vicios_del_consentimiento",
  ],
  ambiental: [
    "autorizacion_cambio_uso_suelo",
    "clausura_profepa",
    "concesion_agua_conagua",
    "dano_ambiental",
    "denuncia_popular_ambiental",
    "descarga_aguas_residuales",
    "emisiones_contaminantes",
    "estudio_riesgo_ambiental",
    "gases_efecto_invernadero",
    "licencia_ambiental_unica",
    "manifestacion_impacto_ambiental",
    "medidas_de_seguridad_profepa",
    "nom_ambiental_incumplimiento",
    "permiso_forestal_conafor",
    "procedimiento_administrativo_profepa",
    "proteccion_areas_naturales_conanp",
    "recurso_de_revision_ambiental",
    "regulacion_industria_hidrocarburos_asea",
    "remediacion_ambiental",
    "residuos_peligrosos",
    "responsabilidad_ambiental_objetiva",
  ],
  inmobiliario: [
    "adeudo_agua",
    "adeudo_cfe",
    "adeudo_hoa",
    "adeudo_predial",
    "cancelacion_hipoteca",
    "catastro",
    "cuenta_predial",
    "discrepancia_medidas",
    "discrepancia_propietario",
    "documento_faltante",
    "documento_vencido",
    "escritura_publica",
    "fideicomiso_zona_restringida",
    "firma_faltante",
    "folio_real",
    "gravamen",
    "hipoteca_vigente",
    "levantamiento_topografico",
    "libertad_de_gravamen",
    "permiso_construccion",
    "poder_notarial",
    "uso_de_suelo",
  ],
};

export const MX_MOTION_TYPES: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "acuerdo_reparatorio",
    "amparo_indirecto_penal",
    "impugnacion_medidas_cautelares",
    "procedimiento_abreviado",
    "recurso_de_apelacion",
    "solicitud_de_no_vinculacion",
    "suspension_condicional",
  ],
  civil: [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "compel",
    "contestacion_demanda",
    "daubert",
    "demanda_civil",
    "discovery",
    "dismiss",
    "expert",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "interplead_escrow",
    "lis_pendens",
    "ofrecimiento_pruebas",
    "preliminary_injunction",
    "protective_order",
    "providencias_precautorias",
    "quiet_title",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "specific_performance",
    "summary_judgment",
    "unlawful_detainer",
  ],
  mercantil: [
    "amend",
    "appointment_of_receiver",
    "asset_purchase_agreement",
    "attachment",
    "board_resolution",
    "books_and_records",
    "breach_of_contract",
    "claim_construction_brief",
    "class_certification",
    "compel",
    "compel_arbitration",
    "confess_judgment",
    "confirm_arbitration",
    "corporate_minutes",
    "daubert",
    "declaratory_judgment",
    "derivative",
    "derivative_action",
    "disclosure_schedule",
    "discovery",
    "dismiss",
    "due_diligence_request",
    "expedited_proceedings",
    "expert",
    "judgment_on_pleadings",
    "lead_plaintiff_motion",
    "markman_hearing",
    "merger_approval",
    "motion_to_dismiss_pslra",
    "partial_summary_judgment",
    "permanent_injunction",
    "preliminary_injunction",
    "protective_order",
    "relief_from_stay",
    "remand",
    "replevin",
    "sanctions",
    "section_220",
    "seizure_order",
    "sequestration",
    "shareholder_consent",
    "specific_performance",
    "stay_pending_arbitration",
    "stock_purchase_agreement",
    "summary_judgment",
    "temporary_restraining_order",
    "tro",
    "vacate_arbitration",
  ],
  familiar: [
    "compel",
    "contempt",
    "custody_modification",
    "discovery",
    "dismiss",
    "petition_for_instructions",
    "petition_for_probate",
    "petition_to_compel_accounting",
    "petition_to_remove_fiduciary",
    "protective_order",
    "summary_judgment",
    "support_modification",
    "temporary_orders",
    "trust_contest",
    "visitation",
    "will_contest",
  ],
  laboral: ["class_certification", "compel", "discovery", "protective_order", "summary_judgment"],
  administrativo: [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "collection_due_process",
    "compel",
    "contestacion_demanda",
    "deficiency",
    "demanda_civil",
    "discovery",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "innocent_spouse",
    "offer_in_compromise",
    "ofrecimiento_pruebas",
    "providencias_precautorias",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "refund_suit",
    "summary_judgment",
    "tax_court_petition",
  ],
  fiscal: [
    "collection_due_process",
    "compel",
    "deficiency",
    "discovery",
    "innocent_spouse",
    "offer_in_compromise",
    "refund_suit",
    "summary_judgment",
    "tax_court_petition",
  ],
  amparo: [
    "demanda_de_amparo",
    "discovery",
    "incidente_de_suspension",
    "preliminary_injunction",
    "qualified_immunity",
    "recurso_de_queja",
    "recurso_de_revision",
    "section_1983",
    "summary_judgment",
  ],
  constitucional: [
    "demanda_de_amparo",
    "discovery",
    "incidente_de_suspension",
    "preliminary_injunction",
    "qualified_immunity",
    "recurso_de_queja",
    "recurso_de_revision",
    "section_1983",
    "summary_judgment",
  ],
  electoral: [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "contestacion_demanda",
    "demanda_civil",
    "discovery",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_pruebas",
    "preliminary_injunction",
    "providencias_precautorias",
    "qualified_immunity",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "section_1983",
    "summary_judgment",
  ],
  agrario: [
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "contestacion_demanda",
    "demanda_civil",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_pruebas",
    "providencias_precautorias",
    "reconvencion",
    "recurso_de_apelacion_civil",
  ],
  ambiental: [
    "amparo_indirecto_ambiental",
    "denuncia_popular",
    "impugnacion_negativa_concesion_conagua",
    "impugnacion_permiso_forestal_conafor",
    "incidente_suspension_profepa",
    "juicio_de_nulidad_ambiental",
    "medidas_cautelares_ambientales",
    "ofrecimiento_pruebas",
    "recurso_de_revision",
  ],
  // Deliberately empty: a closing has no motions. If a real estate matter
  // ever needs one, it has become a dispute — i.e. civil, not inmobiliario.
  inmobiliario: [],
};

export const MX_BLOCKED_TERMS: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "child custody",
    "custody dispute",
    "discrimination claim",
    "district attorney",
    "felony",
    "grand jury",
    "miranda",
    "misdemeanor",
    "payroll records",
    "plea bargain",
    "spousal support",
    "title vii",
    "wrongful termination",
  ],
  civil: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "medical malpractice",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "standard of care",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  mercantil: [
    "brady violation",
    "child custody",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "standard of care",
    "title vii",
    "wrongful termination",
  ],
  familiar: [
    "brady violation",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "standard of care",
    "title vii",
    "wrongful termination",
  ],
  laboral: ["brady violation", "child custody", "criminal procedure", "indictment", "miranda", "spousal support"],
  administrativo: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  fiscal: [
    "child custody",
    "criminal procedure",
    "grand jury",
    "indictment",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "title vii",
    "wrongful termination",
  ],
  amparo: [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support",
  ],
  constitucional: [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support",
  ],
  electoral: [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "divorce",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "payroll records",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  agrario: [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  ambiental: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  inmobiliario: [
    "cross examination",
    "custody dispute",
    "grand jury",
    "hearsay",
    "indictment",
    "jury trial",
    "miranda",
    "motion to dismiss",
    "plea bargain",
    "punitive damages",
    "sentencing",
    "spousal support",
    "subpoena",
    "trial strategy",
    "wrongful termination",
  ],
};

export const MX_FORBIDDEN_REPORT_FIELDS: Record<MexicanCaseType, readonly string[]> = {
  penal: [],
  civil: ["constitutional_issues", "constitutional_issues_struct"],
  mercantil: ["constitutional_issues", "constitutional_issues_struct"],
  familiar: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
  laboral: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
  administrativo: ["constitutional_issues", "constitutional_issues_struct"],
  fiscal: ["constitutional_issues", "constitutional_issues_struct"],
  amparo: [],
  constitucional: [],
  electoral: [],
  agrario: ["constitutional_issues", "constitutional_issues_struct"],
  ambiental: [],
  inmobiliario: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
};
