import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, BookOpen, CheckCircle2, ExternalLink, Map, MapPin, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useI18n } from "@/i18n";
import {
  getResourceNetworkMetadata, saveResourceInstitution, saveResourceKnowledge,
  searchResourceNetwork, submitResourceCorrection, verifyResourceInstitution,
} from "@/lib/social.functions";

type Mode="resources"|"knowledge"|"admin";
type Props={mode:Mode;orgId?:string};
const split=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);

const LABELS={
  status:{verified:["Verificado","Verified"],verification_due:["Verificación vencida","Verification due"],unverified:["Sin verificar","Unverified"],temporarily_unavailable:["No disponible temporalmente","Temporarily unavailable"],at_capacity:["Sin cupo","At capacity"],closed:["Cerrado","Closed"],archived:["Archivado","Archived"]},
  cost:{free:["Gratuito","Free"],sliding_scale:["Cuota variable","Sliding scale"],paid:["De pago","Paid"],public_coverage:["Cobertura pública","Public coverage"],unknown:["Por confirmar","To be confirmed"]},
  capacity:{available:["Disponible","Available"],limited:["Disponibilidad limitada","Limited availability"],at_capacity:["Sin cupo","At capacity"],unknown:["Por confirmar","To be confirmed"]},
  reason:{service_match:["Coincide con el servicio","Service match"],geographic_match:["Coincide con la zona","Geographic match"],language_match:["Coincide con el idioma","Language match"],population_match:["Atiende a esta población","Population match"],emergency_available:["Atención de emergencia","Emergency service"],verified_resource:["Recurso verificado","Verified resource"]},
} as const;
function label(group:keyof typeof LABELS,value:string,es:boolean){const item=(LABELS[group] as Record<string,readonly string[]>)[value];return item?(es?item[0]:item[1]):value.replaceAll("_"," ");}

export function ResourceKnowledgeNetwork({mode,orgId}:Props){
  const {locale}=useI18n();const es=locale==="es";const qc=useQueryClient();
  const metaFn=useServerFn(getResourceNetworkMetadata);const searchFn=useServerFn(searchResourceNetwork);
  const meta=useQuery({queryKey:["resource-network-metadata"],queryFn:()=>metaFn()});
  if(mode==="knowledge")return <KnowledgeCenter es={es} records={meta.data?.knowledge??[]}/>;
  if(mode==="admin")return <ResourceAdministration es={es} orgId={orgId} organizations={meta.data?.organizations??[]} categories={meta.data?.categories??[]} onSaved={()=>{void qc.invalidateQueries({queryKey:["resource-network"]});void qc.invalidateQueries({queryKey:["resource-network-metadata"]});}}/>;
  return <ResourceDirectory es={es} categories={meta.data?.categories??[]} searchFn={searchFn}/>;
}

function ResourceDirectory({es,categories,searchFn}:{es:boolean;categories:any[];searchFn:any}){
  const [filters,setFilters]=useState({query:"",state:"",municipality:"",service:"",urgency:"",population:"",language:"",costType:"",availability:""});
  const [submitted,setSubmitted]=useState(filters);const [view,setView]=useState<"list"|"map">("list");
  const results=useQuery({queryKey:["resource-network",submitted],queryFn:()=>searchFn({data:Object.fromEntries(Object.entries(submitted).filter(([,v])=>v))})});
  const rows=results.data??[];
  return <section className="space-y-4">
    <div className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><MapPin className="h-5 w-5 text-primary"/>{es?"Red de Recursos y Directorio Institucional":"Resource and Institutional Directory"}</h2><p className="mt-1 text-sm text-muted-foreground">{es?"Busque servicios verificados. La búsqueda ordinaria nunca envía datos de personas o casos.":"Search verified services. Ordinary search never sends person or case data."}</p></div><div className="flex rounded-lg border border-border p-1"><button onClick={()=>setView("list")} className={`rounded px-3 py-1.5 text-xs ${view==="list"?"bg-primary text-primary-foreground":""}`}>{es?"Lista":"List"}</button><button onClick={()=>setView("map")} className={`rounded px-3 py-1.5 text-xs ${view==="map"?"bg-primary text-primary-foreground":""}`}><Map className="mr-1 inline h-3.5 w-3.5"/>{es?"Mapa":"Map"}</button></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input label={es?"Nombre o palabra clave":"Name or keyword"} value={filters.query} onChange={v=>setFilters({...filters,query:v})}/><Input label={es?"Estado":"State"} value={filters.state} onChange={v=>setFilters({...filters,state:v})}/><Input label={es?"Municipio":"Municipality"} value={filters.municipality} onChange={v=>setFilters({...filters,municipality:v})}/><Select label={es?"Servicio":"Service"} value={filters.service} onChange={v=>setFilters({...filters,service:v})} options={categories.map((x:any)=>[x.code,es?x.name_es:x.name_en])}/><Select label={es?"Urgencia":"Urgency"} value={filters.urgency} onChange={v=>setFilters({...filters,urgency:v})} options={[["standard",es?"Estándar":"Standard"],["urgent",es?"Urgente":"Urgent"],["emergency",es?"Emergencia":"Emergency"]]}/><Input label={es?"Población atendida":"Population served"} value={filters.population} onChange={v=>setFilters({...filters,population:v})}/><Input label={es?"Idioma":"Language"} value={filters.language} onChange={v=>setFilters({...filters,language:v})}/><Select label={es?"Costo":"Cost"} value={filters.costType} onChange={v=>setFilters({...filters,costType:v})} options={Object.keys(LABELS.cost).map(v=>[v,label("cost",v,es)])}/><Select label={es?"Disponibilidad":"Availability"} value={filters.availability} onChange={v=>setFilters({...filters,availability:v})} options={Object.keys(LABELS.capacity).map(v=>[v,label("capacity",v,es)])}/></div>
      <button onClick={()=>setSubmitted(filters)} className="mt-4 rounded-lg bg-primary px-5 py-2 text-sm font-medium text-primary-foreground"><Search className="mr-2 inline h-4 w-4"/>{es?"Buscar recursos":"Search resources"}</button>
    </div>
    {results.isLoading&&<p className="text-sm text-muted-foreground">{es?"Buscando recursos…":"Searching resources…"}</p>}
    {!results.isLoading&&!rows.length&&<div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground
onst saveFn=useServerFn(saveResourceInstitution);const verifyFn=useServerFn(verifyResourceInstitution);const knowledgeFn=useServerFn(saveResourceKnowledge);
  const [tab,setTab]=useState<"resource"|"verification"|"knowledge">("resource");
  const [resource,setResource]=useState({officialName:"",institutionType:"",description:"",services:"",stateCode:"",municipality:"",address:"",phone:"",whatsapp:"",email:"",website:"",languages:"es",populations:"",eligibility:"",requiredDocuments:"",costType:"unknown",capacityStatus:"unknown",coverageLevels:"municipal",referralMethods:"phone",appointmentRequired:false,walkInAvailable:false,emergencyAvailable:false,remoteAvailable:false,locationConfidential:false,publicNotes:"",internalNotes:""});
  const [verification,setVerification]=useState({institutionId:"",status:"verified",source:"",evidenceUrl:"",notes:"",nextVerificationAt:""});
  const [knowledge,setKnowledge]=useState({titleEs:"",titleEn:"",summaryEs:"",summaryEn:"",knowledgeType:"procedure",serviceCategories:"",stateCodes:"",sourceUrl:"",approvalStatus:"draft",reviewDueAt:""});
  const saveMutation=useMutation({mutationFn:()=>saveFn({data:{orgId:orgId||organizations[0]?.id||null,officialName:resource.officialName,institutionType:resource.institutionType,description:resource.description,services:split(resource.services),stateCode:resource.stateCode,municipality:resource.municipality,address:resource.address,phone:resource.phone,whatsapp:resource.whatsapp,email:resource.email,website:resource.website,languages:split(resource.languages),populations:split(resource.populations),eligibility:resource.eligibility,requiredDocuments:split(resource.requiredDocuments),costType:resource.costType as any,capacityStatus:resource.capacityStatus,coverageLevels:split(resource.coverageLevels),referralMethods:split(resource.referralMethods),appointmentRequired:resource.appointmentRequired,walkInAvailable:resource.walkInAvailable,emergencyAvailable:resource.emergencyAvailable,remoteAvailable:resource.remoteAvailable,locationConfidential:resource.locationConfidential,publicNotes:resource.publicNotes,internalNotes:resource.internalNotes}}),onSuccess:()=>{toast.success(es?"Recurso guardado":"Resource saved");onSaved();},onError:(e:any)=>toast.error(e?.message??String(e))});
  const verifyMutation=useMutation({mutationFn:()=>verifyFn({data:{institutionId:verification.institutionId,status:verification.status as any,source:verification.source,evidenceUrl:verification.evidenceUrl,notes:verification.notes,nextVerificationAt:verification.nextVerificationAt?new Date(verification.nextVerificationAt).toISOString():undefined}}),onSuccess:()=>{toast.success(es?"Verificación registrada":"Verification recorded");onSaved();},onError:(e:any)=>toast.error(e?.message??String(e))});
  const knowledgeMutation=useMutation({mutationFn:()=>knowledgeFn({data:{orgId:orgId||organizations[0]?.id||null,titleEs:knowledge.titleEs,titleEn:knowledge.titleEn,summaryEs:knowledge.summaryEs,summaryEn:knowledge.summaryEn,knowledgeType:knowledge.knowledgeType as any,serviceCategories:split(knowledge.serviceCategories),stateCodes:split(knowledge.stateCodes),sourceUrl:knowledge.sourceUrl,approvalStatus:knowledge.approvalStatus as any,reviewDueAt:knowledge.reviewDueAt?new Date(knowledge.reviewDueAt).toISOString():undefined}}),onSuccess:()=>{toast.success(es?"Conocimiento guardado":"Knowledge saved");onSaved();},onError:(e:any)=>toast.error(e?.message??String(e))});
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><ShieldCheck className="h-5 w-5 text-primary"/>{es?"Administración de recursos y conocimiento":"Resource and knowledge administration"}</h2><div className="mt-4 flex flex-wrap gap-2">{[["resource",es?"Gestionar recursos":"Manage resources"],["verification",es?"Verificación":"Verification"],["knowledge",es?"Gestión del conocimiento":"Knowledge management"]].map(([id,name])=><button key={id} onClick={()=>setTab(id as any)} className={`rounded-lg px-3 py-2 text-xs ${tab===id?"bg-primary text-primary-foreground":"border border-border"}`}>{name}</button>)}</div>
    {tab==="resource"&&<div className="mt-4 grid gap-3 md:grid-cols-2"><Input label={es?"Nombre oficial":"Official name"} value={resource.officialName} onChange={v=>setResource({...resource,officialName:v})}/><Input label={es?"Tipo de institución":"Institution type"} value={resource.institutionType} onChange={v=>setResource({...resource,institutionType:v})}/><Text label={es?"Descripción":"Description"} value={resource.description} onChange={v=>setResource({...resource,description:v})}/><Input label={es?"Servicios (separados por coma)":"Services (comma-separated)"} value={resource.services} onChange={v=>setResource({...resource,services:v})}/><Input label={es?"Estado":"State"} value={resource.stateCode} onChange={v=>setResource({...resource,stateCode:v})}/><Input label={es?"Municipio":"Municipality"} value={resource.municipality} onChange={v=>setResource({...resource,municipality:v})}/><Input label={es?"Domicilio":"Address"} value={resource.address} onChange={v=>setResource({...resource,address:v})}/><Input label={es?"Teléfono":"Telephone"} value={resource.phone} onChange={v=>setResource({...resource,phone:v})}/><Input label="WhatsApp" value={resource.whatsapp} onChange={v=>setResource({...resource,whatsapp:v})}/><Input label="Email" value={resource.email} onChange={v=>setResource({...resource,email:v})}/><Input label={es?"Sitio web":"Website"} value={resource.website} onChange={v=>setResource({...resource,website:v})}/><Input label={es?"Idiomas":"Languages"} value={resource.languages} onChange={v=>setResource({...resource,languages:v})}/><Input label={es?"Poblaciones atendidas":"Populations served"} value={resource.populations} onChange={v=>setResource({...resource,populations:v})}/><Text label={es?"Elegibilidad":"Eligibility"} value={resource.eligibility} onChange={v=>setResource({...resource,eligibility:v})}/><Input label={es?"Documentos requeridos":"Required documents"} value={resource.requiredDocuments} onChange={v=>setResource({...resource,requiredDocuments:v})}/><Select label={es?"Costo":"Cost"} value={resource.costType} onChange={v=>setResource({...resource,costType:v})} options={Object.keys(LABELS.cost).map(v=>[v,label("cost",v,es)])}/><Input label={es?"Métodos de canalización":"Referral methods"} value={resource.referralMethods} onChange={v=>setResource({...resource,referralMethods:v})}/><I
nput label={es?"Cobertura":"Coverage"} value={resource.coverageLevels} onChange={v=>setResource({...resource,coverageLevels:v})}/><Text label={es?"Notas públicas":"Public notes"} value={resource.publicNotes} onChange={v=>setResource({...resource,publicNotes:v})}/><Text label={es?"Notas internas (nunca se comparten)":"Internal notes (never shared)"} value={resource.internalNotes} onChange={v=>setResource({...resource,internalNotes:v})}/><div className="md:col-span-2 flex flex-wrap gap-4">{[["appointmentRequired",es?"Requiere cita":"Appointment required"],["walkInAvailable",es?"Atención sin cita":"Walk-in available"],["emergencyAvailable",es?"Emergencias":"Emergency service"],["remoteAvailable",es?"Servicio remoto":"Remote service"],["locationConfidential",es?"Ubicación confidencial":"Confidential location"]].map(([k,n])=><label key={k} className="text-sm"><input type="checkbox" checked={(resource as any)[k]} onChange={e=>setResource({...resource,[k]:e.target.checked})} className="mr-2"/>{n}</label>)}</div><button disabled={saveMutation.isPending||resource.officialName.length<2||resource.institutionType.length<2} onClick={()=>saveMutation.mutate()} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">{es?"Guardar recurso":"Save resource"}</button></div>}
    {tab==="verification"&&<div className="mt-4 grid gap-3 md:grid-cols-2"><Input label={es?"ID del recurso":"Resource ID"} value={verification.institutionId} onChange={v=>setVerification({...verification,institutionId:v})}/><Select label={es?"Estado":"Status"} value={verification.status} onChange={v=>setVerification({...verification,status:v})} options={Object.keys(LABELS.status).map(v=>[v,label("status",v,es)])}/><Input label={es?"Fuente de verificación":"Verification source"} value={verification.source} onChange={v=>setVerification({...verification,source:v})}/><Input label={es?"Evidencia (URL)":"Evidence (URL)"} value={verification.evidenceUrl} onChange={v=>setVerification({...verification,evidenceUrl:v})}/><Input label={es?"Próxima verificación":"Next verification"} type="date" value={verification.nextVerificationAt} onChange={v=>setVerification({...verification,nextVerificationAt:v})}/><Text label={es?"Notas":"Notes"} value={verification.notes} onChange={v=>setVerification({...verification,notes:v})}/><button disabled={verifyMutation.isPending||!verification.institutionId||verification.source.length<2} onClick={()=>verifyMutation.mutate()} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground"><CheckCircle2 className="mr-2 inline h-4 w-4"/>{es?"Registrar verificación":"Record verification"}</button></div>}
    {tab==="knowledge"&&<div className="mt-4 grid gap-3 md:grid-cols-2"><Input label={es?"Título en español":"Spanish title"} value={knowledge.titleEs} onChange={v=>setKnowledge({...knowledge,titleEs:v})}/><Input label={es?"Título en inglés":"English title"} value={knowledge.titleEn} onChange={v=>setKnowledge({...knowledge,titleEn:v})}/><Text label={es?"Resumen en español":"Spanish summary"} value={knowledge.summaryEs} onChange={v=>setKnowledge({...knowledge,summaryEs:v})}/><Text label={es?"Resumen en inglés":"English summary"} value={knowledge.summaryEn} onChange={v=>setKnowledge({...knowledge,summaryEn:v})}/><Select label={es?"Tipo":"Type"} value={knowledge.knowledgeType} onChange={v=>setKnowledge({...knowledge,knowledgeType:v})} options={[["procedure",es?"Procedimiento":"Procedure"],["protocol",es?"Protocolo":"Protocol"],["manual",es?"Manual":"Manual"],["form",es?"Formulario":"Form"],["legal_update",es?"Actualización jurídica":"Legal update"],["service_guide",es?"Guía de servicio":"Service guide"],["institution_note",es?"Nota institucional":"Institution note"]]}/><Select label={es?"Aprobación":"Approval"} value={knowledge.approvalStatus} onChange={v=>setKnowledge({...knowledge,approvalStatus:v})} options={[["draft",es?"Borrador":"Draft"],["in_review",es?"En revisión":"In review"],["approved",es?"Aprobado":"Approved"],["retired",es?"Retirado":"Retired"]]}/><Input label={es?"Categorías":"Categories"} value={knowledge.serviceCategories} onChange={v=>setKnowledge({...knowledge,serviceCategories:v})}/><Input label={es?"Estados":"States"} value={knowledge.stateCodes} onChange={v=>setKnowledge({...knowledge,stateCodes:v})}/><Input label={es?"Fuente":"Source"} value={knowledge.sourceUrl} onChange={v=>setKnowledge({...knowledge,sourceUrl:v})}/><Input label={es?"Revisión programada":"Scheduled review"} type="date" value={knowledge.reviewDueAt} onChange={v=>setKnowledge({...knowledge,reviewDueAt:v})}/><button disabled={knowledgeMutation.isPending||knowledge.titleEs.length<2||knowledge.titleEn.length<2} onClick={()=>knowledgeMutation.mutate()} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">{es?"Guardar conocimiento":"Save knowledge"}</button></div>}
  </section>;
}

function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-xs font-medium text-muted-foreground">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"/></label>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-xs font-medium text-muted-foreground">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<readonly string[]>}){return <label className="block text-xs font-medium text-muted-foreground">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"><option value="">—</option>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>}

