import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState, type ReactNode } from "react";
import { toast } from "sonner";
import { CheckCircle2, FileUp, Loader2, RefreshCw, ShieldAlert } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/i18n";
import {
  acceptSocialTransfer, advanceSocialTransfer, approveSocialCarePlan,
  assignSocialCaseManager, closeSocialCase, createSocialAppointment,
  createSocialCarePlan, createSocialConsent, createSocialReferral,
  createSocialTransfer, finalizeSocialDocumentUpload, getSocialCase,
  linkSocialImmigrationMatter, prepareSocialDocumentUpload,
  recordSocialAssessment, recordSocialIntervention, refreshSocialAlerts,
  reopenSocialCase, revokeSocialConsent, sendSocialReferral,
  upsertSocialTask, verifySocialReferralResult,
} from "@/lib/social.functions";

type Props={
  caseId:string;
  people:any[];
  institutions:any[];
  templates:any[];
  roleAssignments:any[];
  onClose:()=>void;
};
type Tab="overview"|"assessment"|"plan"|"intervention"|"consent"|"referral"|"tasks"|"documents"|"transfer"|"closure"|"immigration"|"activity";
const TABS:Array<{id:Tab;es:string;en:string}>=[
  {id:"overview",es:"Resumen",en:"Overview"},{id:"assessment",es:"Evaluación",en:"Assessment"},
  {id:"plan",es:"Plan",en:"Care plan"},{id:"intervention",es:"Intervención",en:"Intervention"},
  {id:"consent",es:"Consentimiento",en:"Consent"},{id:"referral",es:"Canalización",en:"Referral"},
  {id:"tasks",es:"Tareas y citas",en:"Tasks & appointments"},{id:"documents",es:"Documentos",en:"Documents"},
  {id:"transfer",es:"Transferencia",en:"Transfer"},{id:"closure",es:"Cierre",en:"Closure"},
  {id:"immigration",es:"Vínculo migratorio",en:"Immigration link"},{id:"activity",es:"Auditoría",en:"Audit"},
];

export function SocialCaseWorkspace({caseId,people,institutions,templates,roleAssignments,onClose}:Props){
  const {locale}=useI18n();const es=locale==="es";const qc=useQueryClient();
  const getCaseFn=useServerFn(getSocialCase);
  const [tab,setTab]=useState<Tab>("overview");
  const detail=useQuery({queryKey:["social-case",caseId],queryFn:()=>getCaseFn({data:{caseId}})});
  const refresh=()=>qc.invalidateQueries({queryKey:["social-case",caseId]});
  const success=(message:string)=>{toast.success(message);void refresh();};
  const caseData=detail.data;
  const c=caseData?.case;
  const person=people.find((p)=>p.id===c?.person_id);
  const caseLabel=c?.case_number??"";
  const caseOrgId=c?.org_id??"";
  const casePersonId=c?.person_id??undefined;
  const caseFamilyId=c?.family_id??undefined;

  const assessmentFn=useServerFn(recordSocialAssessment);
  const [assessment,setAssessment]=useState({riskLevel:"unknown" as "unknown"|"low"|"moderate"|"high"|"critical",reason:"",evidence:"",protective:"",actions:"",followUp:"",review:"",override:false,overrideExplanation:"",templateId:""});
  const assessmentM=useMutation({mutationFn:()=>assessmentFn({data:{socialCaseId:caseId,templateId:assessment.templateId||undefined,riskLevel:assessment.riskLevel,reason:assessment.reason,evidenceObservations:assessment.evidence||undefined,protectiveFactors:assessment.protective||undefined,immediateActions:assessment.actions||undefined,requiredFollowUp:assessment.followUp||undefined,nextReviewDate:assessment.review||undefined,answers:{},professionalOverride:assessment.override,overrideExplanation:assessment.overrideExplanation||undefined}}),onSuccess:()=>success(es?"Evaluación guardada":"Assessment saved"),onError:showError});

  const planFn=useServerFn(createSocialCarePlan);const approveFn=useServerFn(approveSocialCarePlan);
  const [plan,setPlan]=useState({summary:"",need:"",goal:"",action:"",target:"",outcome:""});
  const planM=useMutation({mutationFn:()=>planFn({data:{socialCaseId:caseId,summary:plan.summary,status:"under_review",goals:[{identifiedNeed:plan.need,goal:plan.goal,plannedAction:plan.action,targetDate:plan.target||undefined,priority:"normal",expectedOutcome:plan.outcome||undefined}]}}),onSuccess:()=>success(es?"Plan creado para revisión":"Plan created for review"),onError:showError});
  const approveM=useMutation({mutationFn:(x:{id:string;version:number})=>approveFn({data:{planId:x.id,version:x.version}}),onSuccess:()=>success(es?"Plan aprobado":"Plan approved"),onError:showError});

  const interventionFn=useServerFn(recordSocialIntervention);
  const [intervention,setIntervention]=useState({serviceType:"social_work",reason:"",actions:"",outcome:"",recordType:"general_case_record" as any,followUp:false});
  const interventionM=useMutation({mutationFn:()=>interventionFn({data:{socialCaseId:caseId,occurredAt:new Date().toISOString(),serviceType:intervention.serviceType,reason:intervention.reason,actionsTaken:intervention.actions,outcome:intervention.outcome||undefined,followUpRequired:intervention.followUp,recordType:intervention.recordType,confidentialityLevel:intervention.recordType==="general_case_record"?"standard":"restricted"}}),onSuccess:()=>success(es?"Intervención registrada":"Intervention recorded"),onError:showError});

  const consentFn=useServerFn(createSocialConsent);const revokeFn=useServerFn(revokeSocialConsent);
  const [consent,setConsent]=useState({type:"interinstitutional_data_sharing",consentedBy:"",purposes:"referral",recipients:"",information:"name,contact",restrictions:"",expires:""});
  const consentM=useMutation({mutationFn:()=>consentFn({data:{orgId:caseOrgId,personId:casePersonId??undefined,familyId:caseFamilyId??undefined,consentType:consent.type,language:locale,consentedByName:consent.consentedBy,permittedPurposes:split(consent.purposes),permittedRecipients:split(consent.recipients),permittedInformation:split(consent.information),restrictions:consent.restrictions||undefined,expiresAt:consent.expires?new Date(consent.expires).toISOString():undefined}}),onSuccess:()=>success(es?"Consentimiento versionado":"Consent version recorded"),onError:showError});
  const revokeM=useMutation({mutationFn:(id:string)=>revokeFn({data:{consentId:id,reason:"Revocado por usuario autorizado / Revoked by authorized user"}}),onSuccess:()=>success(es?"Consentimiento revocado":"Consent revoked"),onError:showError});

  const referralFn=useServerFn(createSocialReferral);const sendReferralFn=useServerFn(sendSocialReferral);const verifyReferralFn=useServerFn(verifySocialReferralResult);
  const [referral,setReferral]=useState({institutionId:"",service:"",reason:"",urgency:"normal" as "low"|"normal"|"high"|"urgent",consentId:"",information:"name,contact",result:""});
  const referralM=useMutation({mutationFn:()=>referralFn({data:{socialCaseId:caseId,institutionId:referral.institutionId,serviceRequested:referral.service,reason:referral.reason,urgency:referral.urgency,consentId:referral.consentId||undefined,authorizedInformation:split(referral.information)}}),onSuccess:()=>success(es?"Canalización creada":"Referral created"),onError:showError});
  const sendReferralM=useMutation({mutationFn:(id:string)=>sendReferralFn({data:{referralId:id,purpose:"referral",sharedFields:Object.fromEntries(split(referral.information).map(k=>[k,true]))}}),onSuccess:()=>success(es?"Canalización enviada con consentimiento":"Referral sent with consent"),onError:showError});
  const verifyReferralM=useMutation({mutationFn:(id:string)=>verifyReferralFn({data:{referralId:id,result:referral.result,response:"Resultado verificado por personal autorizado"}}),onSuccess:()=>success(es?"Resultado verificado":"Result verified"),onError:showError});

  const taskFn=useServerFn(upsertSocialTask);const appointmentFn=useServerFn(createSocialAppointment);const alertsFn=useServerFn(refreshSocialAlerts);
  const [task,setTask]=useState({title:"",due:"",priority:"normal" as "low"|"normal"|"high"|"urgent"});
  const [appointment,setAppointment]=useState({title:"",when:"",method:""});
  const taskM=useMutation({mutationFn:()=>taskFn({data:{socialCaseId:caseId,title:task.title,dueAt:task.due?new Date(task.due).toISOString():undefined,priority:task.priority,status:"todo"}}),onSuccess:()=>success(es?"Tarea creada":"Task created"),onError:showError});
  const appointmentM=useMutation({mutationFn:()=>appointmentFn({data:{socialCaseId:caseId,title:appointment.title,scheduledAt:new Date(appointment.when).toISOString(),locationMethod:appointment.method||undefined}}),onSuccess:()=>success(es?"Cita programada":"Appointment scheduled"),onError:showError});
  const alertsM=useMutation({mutationFn:()=>alertsFn({data:{caseId}}),onSuccess:()=>success(es?"Alertas actualizadas":"Alerts refreshed"),onError:showError});

  const prepareFn=useServerFn(prepareSocialDocumentUpload);const finalizeFn=useServerFn(finalizeSocialDocumentUpload);
  const [document,setDocument]=useState({file:null as File|null,title:"",type:"supporting_document",recordType:"general_case_record" as any,sensitivity:"confidential" as any,consentId:""});
  const documentM=useMutation({mutationFn:async()=>{const file=document.file;if(!file)throw new Error(es?"Seleccione un archivo":"Select a file");const prepared=await prepareFn({data:{orgId:caseOrgId,socialCaseId:caseId,recordType:document.recordType,fileName:file.name}});const {error}=await supabase.storage.from("social-case-files").uploadToSignedUrl(prepared.path,prepared.token,file,{contentType:file.type});if(error)throw error;return finalizeFn({data:{socialCaseId:caseId,path:prepared.path,title:document.title||file.name,documentType:document.type,recordType:document.recordType,sensitivity:document.sensitivity,consentId:document.consentId||undefined,extractionAuthorized:false,mimeType:file.type||undefined}});},onSuccess:()=>success(es?"Original protegido y versionado":"Original protected and versioned"),onError:showError});

  const transferFn=useServerFn(createSocialTransfer);const advanceFn=useServerFn(advanceSocialTransfer);const acceptFn=useServerFn(acceptSocialTransfer);
  const [transfer,setTransfer]=useState({type:"case_manager" as any,toUser:"",receivingOrg:"",consentId:"",summary:"",information:"case_summary,tasks,deadlines"});
  const transferM=useMutation({mutationFn:()=>transferFn({data:{socialCaseId:caseId,transferType:transfer.type,toUserId:transfer.toUser||undefined,receivingOrgId:transfer.receivingOrg||undefined,consentId:transfer.consentId||undefined,selectedInformation:Object.fromEntries(split(transfer.information).map(k=>[k,true])),restrictedInformation:{excluded:true},summary:transfer.summary,deadlines:[]}}),onSuccess:()=>success(es?"Transferencia enviada a aprobación":"Transfer submitted for approval"),onError:showError});
  const advanceM=useMutation({mutationFn:(x:{id:string;action:"approve"|"send"|"reject"})=>advanceFn({data:{transferId:x.id,action:x.action}}),onSuccess:()=>success(es?"Transferencia actualizada":"Transfer updated"),onError:showError});
  const acceptM=useMutation({mutationFn:(id:string)=>acceptFn({data:{transferId:id}}),onSuccess:()=>success(es?"Recepción confirmada":"Receipt confirmed"),onError:showError});

  const closeFn=useServerFn(closeSocialCase);const reopenFn=useServerFn(reopenSocialCase);
  const [closure,setClosure]=useState({reason:"services_completed" as any,finalRisk:"unknown" as any,summary:"",reopenReason:""});
  const closeM=useMutation({mutationFn:()=>closeFn({data:{caseId,reason:closure.reason,finalRisk:closure.finalRisk,summary:{goals_completed:closure.summary,client_notification:"recorded",retention_status:"review_pending"}}}),onSuccess:()=>success(es?"Caso cerrado con revisión":"Case closed with review"),onError:showError});
  const reopenM=useMutation({mutationFn:()=>reopenFn({data:{caseId,reason:closure.reopenReason}}),onSuccess:()=>success(es?"Caso reabierto":"Case reopened"),onError:showError});

  const immigrationFn=useServerFn(linkSocialImmigrationMatter);
  const [immigration,setImmigration]=useState({matterId:"",consentId:"",statusFields:"status,deadlines",socialFields:"contact,non_refoulement_concern",documents:""});
  const immigrationM=useMutation({mutationFn:()=>immigrationFn({data:{socialCaseId:caseId,immigrationCaseId:immigration.matterId,consentId:immigration.consentId,permittedStatusFields:split(immigration.statusFields),sharedSocialFields:split(immigration.socialFields),sharedDocumentIds:split(immigration.documents),nonRefoulementConcern:false,detentionDeportationRisk:false}}),onSuccess:()=>success(es?"Vínculo migratorio autorizado":"Immigration link authorized"),onError:showError});

  const assignFn=useServerFn(assignSocialCaseManager);const [assignment,setAssignment]=useState({userId:"",role:"case_manager" as any});
  const assignM=useMutation({mutationFn:()=>assignFn({data:{caseId,userId:assignment.userId,role:assignment.role}}),onSuccess:()=>success(es?"Asignación actualizada":"Assignment updated"),onError:showError});

  if(detail.isLoading||!caseData||!c)return <Panel><Loader2 className="h-5 w-5 animate-spin"/></Panel>;
  return <div className="rounded-2xl border border-primary/25 bg-card shadow-xl">
    <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border p-5">
      <div><p className="font-mono text-sm text-primary">{caseLabel}</p><h2 className="text-xl font-semibold">{person?.legal_name??(es?"Caso familiar":"Family case")}</h2><p className="text-xs text-muted-foreground">{c?.status} · {c.risk_level} · {c.confidentiality_level}</p></div>
      <button onClick={onClose} className="rounded-lg border border-border px-3 py-2 text-sm">{es?"Cerrar espacio":"Close workspace"}</button>
    </div>
    <div className="flex gap-1 overflow-x-auto border-b border-border p-2">{TABS.map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`shrink-0 rounded-md px-3 py-2 text-xs ${tab===x.id?"bg-primary text-primary-foreground":"hover:bg-muted"}`}>{es?x.es:x.en}</button>)}</div>
    <div className="p-5">
      {tab==="overview"&&<div className="grid gap-4 md:grid-cols-2"><History title={es?"Estado del caso":"Case status"} rows={[c]} render={(x)=><p>{x.case_number} · {x.status} · {x.risk_level}</p>}/><Panel><h3 className="font-semibold">{es?"Asignación profesional":"Professional assignment"}</h3><Select label={es?"Usuario autorizado":"Authorized user"} value={assignment.userId} onChange={v=>setAssignment({...assignment,userId:v})} options={roleAssignments.map((r:any)=>({value:r.user_id,label:`${r.user_id.slice(0,8)} · ${r.role}`}))}/><Select label={es?"Función":"Role"} value={assignment.role} onChange={v=>setAssignment({...assignment,role:v})} options={["case_manager","supervisor","attorney","psychologist","social_worker"].map(v=>({value:v,label:v}))}/><Action busy={assignM.isPending} disabled={!assignment.userId} onClick={()=>assignM.mutate()}>{es?"Asignar":"Assign"}</Action></Panel></div>}

      {tab==="assessment"&&<Two><Panel><h3 className="font-semibold">{es?"Nueva versión de evaluación":"New assessment version"}</h3><Select label={es?"Plantilla":"Template"} value={assessment.templateId} onChange={v=>setAssessment({...assessment,templateId:v})} options={templates.map((t:any)=>({value:t.id,label:es?t.name_es:t.name_en}))}/><Select label={es?"Nivel de riesgo":"Risk level"} value={assessment.riskLevel} onChange={v=>setAssessment({...assessment,riskLevel:v as any})} options={["unknown","low","moderate","high","critical"].map(v=>({value:v,label:v}))}/><Text label={es?"Razón":"Reason"} value={assessment.reason} onChange={v=>setAssessment({...assessment,reason:v})}/><Text label={es?"Evidencia u observaciones":"Evidence or observations"} value={assessment.evidence} onChange={v=>setAssessment({...assessment,evidence:v})}/><Text label={es?"Factores protectores":"Protective factors"} value={assessment.protective} onChange={v=>setAssessment({...assessment,protective:v})}/><Text label={es?"Acciones inmediatas":"Immediate actions"} value={assessment.actions} onChange={v=>setAssessment({...assessment,actions:v})}/><Text label={es?"Seguimiento requerido":"Required follow-up"} value={assessment.followUp} onChange={v=>setAssessment({...assessment,followUp:v})}/><Input label={es?"Fecha de revisión":"Review date"} type="date" value={assessment.review} onChange={v=>setAssessment({...assessment,review:v})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={assessment.override} onChange={e=>setAssessment({...assessment,override:e.target.checked})}/>{es?"Anulación profesional explicada":"Explained professional override"}</label>{assessment.override&&<Text label={es?"Explicación":"Explanation"} value={assessment.overrideExplanation} onChange={v=>setAssessment({...assessment,overrideExplanation:v})}/>}<Action busy={assessmentM.isPending} disabled={!assessment.reason} onClick={()=>assessmentM.mutate()}>{es?"Guardar versión":"Save version"}</Action></Panel><History title={es?"Historial inmutable":"Immutable history"} rows={caseData.assessments} render={(x)=><p>{x.assessment_date?.slice(0,10)} · {x.risk_level} · v{x.current_version}</p>}/></Two>}

      {tab==="plan"&&<Two><Panel><h3 className="font-semibold">{es?"Nuevo plan de atención":"New care plan"}</h3><Text label={es?"Resumen":"Summary"} value={plan.summary} onChange={v=>setPlan({...plan,summary:v})}/><Text label={es?"Necesidad":"Identified need"} value={plan.need} onChange={v=>setPlan({...plan,need:v})}/><Text label={es?"Meta":"Goal"} value={plan.goal} onChange={v=>setPlan({...plan,goal:v})}/><Text label={es?"Acción prevista":"Planned action"} value={plan.action} onChange={v=>setPlan({...plan,action:v})}/><Input label={es?"Fecha objetivo":"Target date"} type="date" value={plan.target} onChange={v=>setPlan({...plan,target:v})}/><Text label={es?"Resultado esperado":"Expected outcome"} value={plan.outcome} onChange={v=>setPlan({...plan,outcome:v})}/><Action busy={planM.isPending} disabled={!plan.summary||!plan.need||!plan.goal||!plan.action} onClick={()=>planM.mutate()}>{es?"Enviar a revisión":"Submit for review"}</Action></Panel><History title={es?"Planes versionados":"Versioned plans"} rows={caseData.plans} render={(x)=><div><p>{x.status} · v{x.current_version}</p>{x.status==="under_review"&&<button onClick={()=>approveM.mutate({id:x.id,version:x.current_version})} className="text-xs text-primary underline">{es?"Aprobar":"Approve"}</button>}</div>}/></Two>}

      {tab==="intervention"&&<Two><Panel><h3 className="font-semibold">{es?"Registrar intervención":"Record intervention"}</h3><Select label={es?"Servicio":"Service"} value={intervention.serviceType} onChange={v=>setIntervention({...intervention,serviceType:v})} options={["social_work","legal_assistance","immigration_assistance","psychological_support","medical_referral","child_protection","shelter_housing","food_assistance","employment","education","transportation","emergency","documentation","family_reunification","institutional_advocacy"].map(v=>({value:v,label:v}))}/><Select label={es?"Tipo de registro":"Record type"} value={intervention.recordType} onChange={v=>setIntervention({...intervention,recordType:v})} options={recordOptions}/><Text label={es?"Razón":"Reason"} value={intervention.reason} onChange={v=>setIntervention({...intervention,reason:v})}/><Text label={es?"Acciones realizadas":"Actions taken"} value={intervention.actions} onChange={v=>setIntervention({...intervention,actions:v})}/><Text label={es?"Resultado":"Outcome"} value={intervention.outcome} onChange={v=>setIntervention({...intervention,outcome:v})}/><Action busy={interventionM.isPending} disabled={!intervention.reason||!intervention.actions} onClick={()=>interventionM.mutate()}>{es?"Registrar":"Record"}</Action></Panel><History title={es?"Intervenciones autorizadas":"Authorized interventions"} rows={caseData.interventions} render={(x)=><p>{x.service_type} · {x.record_type} · {new Date(x.occurred_at).toLocaleDateString()}</p>}/></Two>}

      {tab==="consent"&&<Two><Panel><h3 className="font-semibold">{es?"Consentimiento informado":"Informed consent"}</h3><Input label={es?"Tipo":"Type"} value={consent.type} onChange={v=>setConsent({...consent,type:v})}/><Input label={es?"Persona que consiente":"Person consenting"} value={consent.consentedBy} onChange={v=>setConsent({...consent,consentedBy:v})}/><Input label={es?"Propósitos (comas)":"Purposes (commas)"} value={consent.purposes} onChange={v=>setConsent({...consent,purposes:v})}/><Input label={es?"Destinatarios (IDs o nombres)":"Recipients (IDs or names)"} value={consent.recipients} onChange={v=>setConsent({...consent,recipients:v})}/><Input label={es?"Información permitida":"Permitted information"} value={consent.information} onChange={v=>setConsent({...consent,information:v})}/><Text label={es?"Restricciones":"Restrictions"} value={consent.restrictions} onChange={v=>setConsent({...consent,restrictions:v})}/><Input label={es?"Expira":"Expires"} type="datetime-local" value={consent.expires} onChange={v=>setConsent({...consent,expires:v})}/><Action busy={consentM.isPending} disabled={!consent.consentedBy||!consent.recipients} onClick={()=>consentM.mutate()}>{es?"Guardar consentimiento":"Record consent"}</Action></Panel><History title={es?"Versiones y estado":"Versions and status"} rows={caseData.consents} render={(x)=><div><p>{x.consent_type} · {x.status} · v{x.current_version}</p>{x.status==="active"&&<button onClick={()=>revokeM.mutate(x.id)} className="text-xs text-destructive underline">{es?"Revocar":"Revoke"}</button>}</div>}/></Two>}

      {tab==="referral"&&<Two><Panel><h3 className="font-semibold">{es?"Nueva canalización":"New referral"}</h3><Select label={es?"Institución":"Institution"} value={referral.institutionId} onChange={v=>setReferral({...referral,institutionId:v})} options={institutions.map((i:any)=>({value:i.id,label:i.name}))}/><Input label={es?"Servicio solicitado":"Service requested"} value={referral.service} onChange={v=>setReferral({...referral,service:v})}/><Text label={es?"Razón":"Reason"} value={referral.reason} onChange={v=>setReferral({...referral,reason:v})}/><Select label={es?"Consentimiento":"Consent"} value={referral.consentId} onChange={v=>setReferral({...referral,consentId:v})} options={caseData.consents.filter((x:any)=>x.status==="active").map((x:any)=>({value:x.id,label:`${x.consent_type} · v${x.current_version}`}))}/><Input label={es?"Información autorizada":"Authorized information"} value={referral.information} onChange={v=>setReferral({...referral,information:v})}/><Action busy={referralM.isPending} disabled={!referral.institutionId||!referral.service||!referral.reason} onClick={()=>referralM.mutate()}>{es?"Crear canalización":"Create referral"}</Action></Panel><History title={es?"Seguimiento":"Tracking"} rows={caseData.referrals} render={(x)=><div><p>{x.referral_number} · {x.status}</p>{["draft","awaiting_consent"].includes(x.status)&&x.consent_id&&<button onClick={()=>sendReferralM.mutate(x.id)} className="mr-3 text-xs text-primary underline">{es?"Enviar":"Send"}</button>}{["sent","received","appointment_scheduled","in_progress"].includes(x.status)&&<><input value={referral.result} onChange={e=>setReferral({...referral,result:e.target.value})} placeholder={es?"Resultado verificado":"Verified result"} className="mt-2 rounded border border-border px-2 py-1 text-xs"/><button onClick={()=>verifyReferralM.mutate(x.id)} className="ml-2 text-xs text-primary underline">{es?"Verificar conclusión":"Verify completion"}</button></>}</div>}/></Two>}

      {tab==="tasks"&&<div className="grid gap-4 xl:grid-cols-3"><Panel><h3 className="font-semibold">{es?"Nueva tarea":"New task"}</h3><Input label={es?"Título":"Title"} value={task.title} onChange={v=>setTask({...task,title:v})}/><Input label={es?"Vence":"Due"} type="datetime-local" value={task.due} onChange={v=>setTask({...task,due:v})}/><Action busy={taskM.isPending} disabled={!task.title} onClick={()=>taskM.mutate()}>{es?"Crear tarea":"Create task"}</Action><button onClick={()=>alertsM.mutate()} className="mt-3 text-xs text-primary underline"><RefreshCw className="mr-1 inline h-3 w-3"/>{es?"Actualizar alertas":"Refresh alerts"}</button></Panel><Panel><h3 className="font-semibold">{es?"Nueva cita":"New appointment"}</h3><Input label={es?"Título":"Title"} value={appointment.title} onChange={v=>setAppointment({...appointment,title:v})}/><Input label={es?"Fecha y hora":"Date and time"} type="datetime-local" value={appointment.when} onChange={v=>setAppointment({...appointment,when:v})}/><Input label={es?"Lugar o método":"Location or method"} value={appointment.method} onChange={v=>setAppointment({...appointment,method:v})}/><Action busy={appointmentM.isPending} disabled={!appointment.title||!appointment.when} onClick={()=>appointmentM.mutate()}>{es?"Programar":"Schedule"}</Action></Panel><History title={es?"Pendientes":"Pending"} rows={[...caseData.tasks,...caseData.appointments]} render={(x)=><p>{x.title} · {(x.due_at??x.scheduled_at)?.slice(0,16)}</p>}/></div>}

      {tab==="documents"&&<Two><Panel><h3 className="font-semibold">{es?"Cargar original privado":"Upload private original"}</h3><input type="file" accept=".pdf,.docx,.jpg,.jpeg,.png,.webp,.zip" onChange={e=>setDocument({...document,file:e.target.files?.[0]??null,title:e.target.files?.[0]?.name??document.title})} className="w-full text-sm"/><Input label={es?"Título":"Title"} value={document.title} onChange={v=>setDocument({...document,title:v})}/><Select label={es?"Tipo de registro":"Record type"} value={document.recordType} onChange={v=>setDocument({...document,recordType:v})} options={recordOptions}/><Select label={es?"Consentimiento aplicable":"Applicable consent"} value={document.consentId} onChange={v=>setDocument({...document,consentId:v})} options={caseData.consents.filter((x:any)=>x.status==="active").map((x:any)=>({value:x.id,label:x.consent_type}))}/><Action busy={documentM.isPending} disabled={!document.file} onClick={()=>documentM.mutate()}><FileUp className="mr-2 inline h-4 w-4"/>{es?"Proteger y registrar":"Protect and register"}</Action></Panel><History title={es?"Documentos autorizados":"Authorized documents"} rows={caseData.documents} render={(x)=><p>{x.title} · v{x.current_version} · {x.record_type}<span className="block font-mono text-[10px] text-muted-foreground">{x.checksum?.slice(0,16)}…</span></p>}/></Two>}

      {tab==="transfer"&&<Two><Panel><h3 className="font-semibold">{es?"Preparar transferencia":"Prepare transfer"}</h3><Select label={es?"Tipo":"Type"} value={transfer.type} onChange={v=>setTransfer({...transfer,type:v})} options={["case_manager","office","service_team","external_organization","social_to_legal","legal_to_social"].map(v=>({value:v,label:v}))}/><Input label={es?"Usuario receptor (UUID)":"Receiving user (UUID)"} value={transfer.toUser} onChange={v=>setTransfer({...transfer,toUser:v})}/><Input label={es?"Organización receptora (UUID)":"Receiving organization (UUID)"} value={transfer.receivingOrg} onChange={v=>setTransfer({...transfer,receivingOrg:v})}/><Select label={es?"Consentimiento":"Consent"} value={transfer.consentId} onChange={v=>setTransfer({...transfer,consentId:v})} options={caseData.consents.filter((x:any)=>x.status==="active").map((x:any)=>({value:x.id,label:x.consent_type}))}/><Input label={es?"Información seleccionada":"Selected information"} value={transfer.information} onChange={v=>setTransfer({...transfer,information:v})}/><Text label={es?"Resumen de transferencia":"Transfer summary"} value={transfer.summary} onChange={v=>setTransfer({...transfer,summary:v})}/><Action busy={transferM.isPending} disabled={!transfer.summary||(!transfer.toUser&&!transfer.receivingOrg)} onClick={()=>transferM.mutate()}>{es?"Solicitar aprobación":"Request approval"}</Action></Panel><History title={es?"Historial completo":"Complete history"} rows={caseData.transfers} render={(x)=><div><p>{x.transfer_type} · {x.status}</p>{x.status==="pending_approval"&&<button onClick={()=>advanceM.mutate({id:x.id,action:"approve"})} className="mr-2 text-xs text-primary underline">{es?"Aprobar":"Approve"}</button>}{x.status==="approved"&&<button onClick={()=>advanceM.mutate({id:x.id,action:"send"})} className="mr-2 text-xs text-primary underline">{es?"Enviar":"Send"}</button>}{x.status==="sent"&&<button onClick={()=>acceptM.mutate(x.id)} className="text-xs text-primary underline">{es?"Confirmar recepción":"Confirm receipt"}</button>}</div>}/></Two>}

      {tab==="closure"&&<Two><Panel><h3 className="font-semibold">{es?"Revisión de cierre":"Closure review"}</h3><Select label={es?"Motivo":"Reason"} value={closure.reason} onChange={v=>setClosure({...closure,reason:v})} options={["services_completed","client_withdrew","unable_to_contact","transferred","ineligible","relocated","duplicate_case","other"].map(v=>({value:v,label:v}))}/><Select label={es?"Riesgo final":"Final risk"} value={closure.finalRisk} onChange={v=>setClosure({...closure,finalRisk:v})} options={["unknown","low","moderate","high","critical"].map(v=>({value:v,label:v}))}/><Text label={es?"Metas y resumen final":"Goals and final summary"} value={closure.summary} onChange={v=>setClosure({...closure,summary:v})}/><Action busy={closeM.isPending} disabled={c?.status==="closed"||!closure.summary} onClick={()=>closeM.mutate()}>{es?"Aprobar cierre":"Approve closure"}</Action>{c?.status==="closed"&&<><Text label={es?"Razón para reabrir":"Reason to reopen"} value={closure.reopenReason} onChange={v=>setClosure({...closure,reopenReason:v})}/><Action busy={reopenM.isPending} disabled={!closure.reopenReason} onClick={()=>reopenM.mutate()}>{es?"Reabrir preservando cierre":"Reopen preserving closure"}</Action></>}</Panel><History title={es?"Historial de cierre":"Closure history"} rows={caseData.closures} render={(x)=><p>v{x.closure_version} · {x.closure_reason} · {x.final_risk_level}</p>}/></Two>}

      {tab==="immigration"&&<Panel><div className="mb-3 flex gap-2 rounded-lg border border-warning/30 bg-warning/10 p-3 text-sm"><ShieldAlert className="h-4 w-4"/>{es?"Solo asuntos mexicanos de Derecho Migratorio, Refugio y Nacionalidad. Se comparte exactamente lo seleccionado.":"Mexican Immigration, Refugee and Nationality matters only. Exactly the selected information is shared."}</div><Input label={es?"ID del asunto migratorio":"Immigration matter ID"} value={immigration.matterId} onChange={v=>setImmigration({...immigration,matterId:v})}/><Select label={es?"Consentimiento específico":"Specific consent"} value={immigration.consentId} onChange={v=>setImmigration({...immigration,consentId:v})} options={caseData.consents.filter((x:any)=>x.status==="active").map((x:any)=>({value:x.id,label:x.consent_type}))}/><Input label={es?"Campos de estado recibidos":"Status fields received"} value={immigration.statusFields} onChange={v=>setImmigration({...immigration,statusFields:v})}/><Input label={es?"Campos sociales compartidos":"Social fields shared"} value={immigration.socialFields} onChange={v=>setImmigration({...immigration,socialFields:v})}/><Action busy={immigrationM.isPending} disabled={!immigration.matterId||!immigration.consentId} onClick={()=>immigrationM.mutate()}>{es?"Crear vínculo autorizado":"Create authorized link"}</Action></Panel>}

      {tab==="activity"&&<History title={es?"Libro de auditoría inmutable":"Immutable audit ledger"} rows={caseData.activity} render={(x)=><p>{new Date(x.occurred_at).toLocaleString()} · {x.event_type} · {x.entity_type}</p>}/>}
    </div>
  </div>;
}

function showError(e:unknown){toast.error(e instanceof Error?e.message:String(e))}
function split(v:string){return v.split(",").map(x=>x.trim()).filter(Boolean)}
const recordOptions=["general_case_record","social_work_record","legal_privileged_record","psychosocial_restricted_record","medical_restricted_record","child_protection_restricted_record"].map(v=>({value:v,label:v}));
function Panel({children}:{children:ReactNode}){return <section className="space-y-3 rounded-xl border border-border bg-card p-4">{children}</section>}
function Two({children}:{children:ReactNode}){return <div className="grid gap-4 xl:grid-cols-2">{children}</div>}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-xs font-medium text-muted-foreground">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"/></label>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-xs font-medium text-muted-foreground">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<{value:string;label:string}>}){return <label className="block text-xs font-medium text-muted-foreground">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="">—</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Action({children,onClick,busy,disabled=false}:{children:ReactNode;onClick:()=>void;busy:boolean;disabled?:boolean}){return <button type="button" onClick={onClick} disabled={busy||disabled} className="w-full rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy&&<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>}{children}</button>}
function History({title,rows,render}:{title:string;rows:any[];render:(x:any)=>ReactNode}){return <Panel><h3 className="font-semibold">{title}</h3>{rows.length?rows.map((x,i)=><div key={x.id??i} className="rounded-lg border border-border p-3 text-sm">{render(x)}</div>):<p className="text-sm text-muted-foreground">—</p>}</Panel>}
